models/Users.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "users".
 *
 * @property integer $id
 * * @property integer $cliente_id
 * @property string $username
 * @property string $email
 * @property string $password
 * @property string $authKey
 * @property string $accessToken
 * @property integer $activate
 * @property integer $role
 * @property string $nombres
 * @property string $apellidos
 * @property string $foto
 */
class Users extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'users';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombres', 'apellidos', 'numeroIdentificacion', 'direccion' ,'telefono' ,'username', 'email','role', 'password'], 'required'],
            [['activate','numeroIdentificacion'], 'integer'],
            [['foto','role'], 'string'],
            [['username'], 'string', 'max' => 50],
            [['email'], 'string', 'max' => 80],
            [['email'], 'email'],
            [['password', 'authKey', 'accessToken'], 'string', 'max' => 250],
            [['direccion'], 'string', 'max' => 150],
            ['password', 'match', 'pattern' => "/^.{8,16}$/", 'message' => 'Mínimo 6 y máximo 16 caracteres'],
            [['nombres', 'apellidos'], 'string', 'max' => 60],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Username',
            'email' => 'Email',
            'password' => 'Password',
            'authKey' => 'Auth Key',
            'accessToken' => 'Access Token',
            'activate' => 'Activate',
            'role' => 'Role',
            'nombres' => 'Nombres',
            'apellidos' => 'Apellidos',
            'foto' => 'Foto',
        ];
    }

    public function getRol()
    {
        return $this->hasOne(Rol::className(), ['id' => 'role']);
    }

 /*     public function email_existe($attribute, $params)
      {
    
    //Buscar el email en la tabla
    $table = Users::find()->where("email=:email", [":email" => $this->email]);
    
    //Si el email existe mostrar el error
    if ($table->count() == 1)
    {
      $this->addError($attribute, "El email seleccionado existe");
    }
      }
    */
      public function username_existe($attribute, $params)
      {
    //Buscar el username en la tabla
    $table = Users::find()->where("username=:username", [":username" => $this->username]);
    
    //Si el username existe mostrar el error
    if ($table->count() == 1)
    {
                  $this->addError($attribute, "El usuario seleccionado existe");
    }
      }
    
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\Soporteequipos;
use app\models\ContactForm;
use yii\web\Response;
use app\models\FormRegister; 
use app\models\Users; 
use yii\widgets\ActiveForm;
use app\models\User;
use app\models\Rol;
use yii\db\Query;
use yii\data\Pagination;
use app\models\FormSearch;
use app\models\OpcionMenu;
use app\models\ItemMenu;
use app\models\SubitemMenu;
use app\models\Menuperfil;
use app\models\Controlusuariomenu;
use app\models\AccesosDirectos; 


use yii\helpers\Html;


class SiteController extends Controller
{
   public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => [ 'user', 'admin','index','register'],
                'rules' => [
                    [
                        //El administrador tiene permisos sobre las siguientes acciones
                        'actions' => ['logout', 'admin','index','register'],
                        //Esta propiedad establece que tiene permisos
                        'allow' => true,
                        //Usuarios autenticados, el signo ? es para invitados
                        'roles' => ['@'],
                        //Este método nos permite crear un filtro sobre la identidad del usuario
                        //y así establecer si tiene permisos o no
                        'matchCallback' => function ($rule, $action) {
                            //Llamada al método que comprueba si es un administrador
                            return User::isUserAdmin(Yii::$app->user->identity->id);
                        },
                    ],
                    [
                       //Los usuarios simples tienen permisos sobre las siguientes acciones
                       'actions' => ['logout', 'user','index'],
                       //Esta propiedad establece que tiene permisos
                       'allow' => true,
                       //Usuarios autenticados, el signo ? es para invitados
                       'roles' => ['@'],
                       //Este método nos permite crear un filtro sobre la identidad del usuario
                       //y así establecer si tiene permisos o no
                       'matchCallback' => function ($rule, $action) {
                          //Llamada al método que comprueba si es un usuario simple
                          return User::isUserVentas(Yii::$app->user->identity->id);
                      },
                   ],
                   [
                       //Los usuarios simples tienen permisos sobre las siguientes acciones
                       'actions' => ['logout', 'user','index'],
                       //Esta propiedad establece que tiene permisos
                       'allow' => true,
                       //Usuarios autenticados, el signo ? es para invitados
                       'roles' => ['@'],
                       //Este método nos permite crear un filtro sobre la identidad del usuario
                       //y así establecer si tiene permisos o no
                       'matchCallback' => function ($rule, $action) {
                          //Llamada al método que comprueba si es un usuario simple
                          return User::isUserTesoreria(Yii::$app->user->identity->id);
                      },
                   ],
                   [
                       //Los usuarios simples tienen permisos sobre las siguientes acciones
                       'actions' => ['logout', 'user','index'],
                       //Esta propiedad establece que tiene permisos
                       'allow' => true,
                       //Usuarios autenticados, el signo ? es para invitados
                       'roles' => ['@'],
                       //Este método nos permite crear un filtro sobre la identidad del usuario
                       //y así establecer si tiene permisos o no
                       'matchCallback' => function ($rule, $action) {
                          //Llamada al método que comprueba si es un usuario simple
                          return User::isUserComercial(Yii::$app->user->identity->id);
                      },
                   ],
                   [
                       //Los usuarios simples tienen permisos sobre las siguientes acciones
                       'actions' => ['logout', 'user','index'],
                       //Esta propiedad establece que tiene permisos
                       'allow' => true,
                       //Usuarios autenticados, el signo ? es para invitados
                       'roles' => ['@'],
                       //Este método nos permite crear un filtro sobre la identidad del usuario
                       //y así establecer si tiene permisos o no
                       'matchCallback' => function ($rule, $action) {
                          //Llamada al método que comprueba si es un usuario simple
                          return User::isUserAlmacen(Yii::$app->user->identity->id);
                      },
                   ],
                   [
                       //Los usuarios simples tienen permisos sobre las siguientes acciones
                       'actions' => ['logout', 'user','index'],
                       //Esta propiedad establece que tiene permisos
                       'allow' => true,
                       //Usuarios autenticados, el signo ? es para invitados
                       'roles' => ['@'],
                       //Este método nos permite crear un filtro sobre la identidad del usuario
                       //y así establecer si tiene permisos o no
                       'matchCallback' => function ($rule, $action) {
                          //Llamada al método que comprueba si es un usuario simple
                          return User::isUserProgramador(Yii::$app->user->identity->id);
                      },
                   ],

                   [
                       //Los usuarios simples tienen permisos sobre las siguientes acciones
                       'actions' => ['logout', 'user','index'],
                       //Esta propiedad establece que tiene permisos
                       'allow' => true,
                       //Usuarios autenticados, el signo ? es para invitados
                       'roles' => ['@'],
                       //Este método nos permite crear un filtro sobre la identidad del usuario
                       //y así establecer si tiene permisos o no
                       'matchCallback' => function ($rule, $action) {
                          //Llamada al método que comprueba si es un usuario simple
                          return User::isUserDigitador(Yii::$app->user->identity->id);
                      },
                   ],
                   [
                        //Los usuarios simples tienen permisos sobre las siguientes acciones
                        'actions' => ['logout', 'user','index'],
                        //Esta propiedad establece que tiene permisos
                        'allow' => true,
                        //Usuarios autenticados, el signo ? es para invitados
                        'roles' => ['@'],
                        //Este método nos permite crear un filtro sobre la identidad del usuario
                        //y así establecer si tiene permisos o no
                        'matchCallback' => function ($rule, $action) {
                            //Llamada al método que comprueba si es un usuario simple
                            return User::isConductor(Yii::$app->user->identity->id);
                        },
                    ],
                    [
                        //Los usuarios simples tienen permisos sobre las siguientes acciones
                        'actions' => ['logout', 'user','index'],
                        //Esta propiedad establece que tiene permisos
                        'allow' => true,
                        //Usuarios autenticados, el signo ? es para invitados
                        'roles' => ['@'],
                        //Este método nos permite crear un filtro sobre la identidad del usuario
                        //y así establecer si tiene permisos o no
                        'matchCallback' => function ($rule, $action) {
                            //Llamada al método que comprueba si es un usuario simple
                            return User::isUserAuxiliar(Yii::$app->user->identity->id);
                        },
                    ],

                    [
                        //Los usuarios simples tienen permisos sobre las siguientes acciones
                        'actions' => ['logout', 'user','index'],
                        //Esta propiedad establece que tiene permisos
                        'allow' => true,
                        //Usuarios autenticados, el signo ? es para invitados
                        'roles' => ['@'],
                        //Este método nos permite crear un filtro sobre la identidad del usuario
                        //y así establecer si tiene permisos o no
                        'matchCallback' => function ($rule, $action) {
                            //Llamada al método que comprueba si es un usuario simple
                            return User::isCompras(Yii::$app->user->identity->id);
                        },
                    ],

                ],
            ],
     //Controla el modo en que se accede a las acciones, en este ejemplo a la acción logout
     //sólo se puede acceder a través del método post
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post','get'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/admin.php
<h1>vista administrador</h1>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name') ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;
use yii\helpers\Url;

$this->title = $name;
?>
<div class="col-lg-12">

    <div class="jumbotron">
        <img width="250" src="<?php echo Url::base(); ?>/images/f52610_b3fa64f9ff4d4ac0a9d8f745fa6b0a82.png" alt="..." class="">
    </div>

    <!-- <h1><?= Html::encode($this->title) ?></h1> -->

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>


    <p>
        Por favor contactese con el area de Tecnologia. Gracias
    </p>

</div>

views/site/index.php
<?php 
    use yii\helpers\Html;
    use yii\helpers\Url;
    use app\models\Users;
    use yii\bootstrap4\ActiveForm;
    $this->title = 'Panel de Control';
?>
  <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->
    <!-- /.content-header -->
    <div class="row">
        <?php if ( in_array(1, $accesosDirectos) ) { // CANTIDAD DE EQUIPOS ?>
            <div class="col-lg-6 col-xs-12">            
                <!-- small box -->
                <div class="small-box bg-primary">
                    <div class="inner">
                        <center><h3>Cantidad de equipos</h3></center>
                        <center><h4 class="btn btn-dark"><?php foreach($equipos as $e){} echo $e['cuenta']?></h4></center>
                    </div>
                    <div class="icon">
                     <i class="fas fa-laptop"></i>
                    </div>
                    <a href="<?php echo Url::base(); ?>/index.php?r=equipos%2Findex" class="small-box-footer">Ir al Módulo <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>  
        <?php } ?>
        <?php if ( in_array(2, $accesosDirectos) ) { // CANTIDAD DE LICENCIAS ?>
            <div class="col-lg-6 col-xs-12">
            <!-- small box -->
                <div class="small-box bg-warning">
                    <div class="inner">
                        <center><h3>Cantidad de licencias </h3></center>
                        <center><h4 class="btn btn-dark"><?php foreach($licencias as $l){} echo $l['cuenta']?></h4></center>
                    </div>
                    <div class="icon">
                     <i class="fab fa-microsoft"></i>
                    </div>
                    <a href="<?php echo Url::base(); ?>/index.php?r=licencias%2Findex" class="small-box-footer">Ir al Módulo <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
        <?php } ?>
        <?php if ( in_array(3, $accesosDirectos) ) { // CRONOGRAMA DE MANTENIMIENTO ?>
            <div class="col-lg-6 col-xs-12">
            <!-- small box -->
                <div class="small-box bg-danger">
                    <div class="inner">
                        <center><h3>Cronogramas de Mantenimiento </h3></center>
                        <center><p>
                            <?= Html::a('Ver Pendientes', ['cronogramas/index'], ['class' => 'btn btn-dark']) ?>                            
                        </p></center>
                    </div>
                    <div class="icon">
                    <i class="fas fa-calendar-alt"></i>
                    </div>
                    <a href="<?php echo Url::base(); ?>/index.php?r=cronogramas%2Findex" class="small-box-footer">Ir al Módulo <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
        <?php } ?> 
        <?php if ( in_array(4, $accesosDirectos) ) { // ESTADISTICAS ?>
            <div class="col-lg-6 col-xs-12">
            <!-- small box -->
                <div class="small-box bg-success">
                    <div class="inner">
                        <center><h3>Estadisticas </h3></center>
                        <center><p>
                            <?= Html::a('Estadistica equipos', ['estadisticas/estadisticasequipos'], ['class' => 'btn btn-dark']) ?>
                            <?= Html::a('Estadistica licencias', ['estadisticas/estadisticaslicencias'], ['class' => 'btn btn-dark']) ?>
                            <?= Html::a('Estadistica Cronogramas', ['estadisticas/estadisticascronogramas'], ['class' => 'btn btn-dark ']) ?>
                            <?= Html::a('Estadistica Soportes', ['estadisticas/estadisticassoportes'], ['class' => 'btn btn-dark ']) ?>
                        </p></center>
                    </div>
                    <div class="icon">
                    <i class="fas fa-chart-line"></i>
                    </div>
                    <a href="<?php echo Url::base(); ?>/index.php?r=estadisticas%2Festadisticasequipos" class="small-box-footer">Ir al Módulo <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
        <?php } ?> 
        <?php if ( in_array(4, $accesosDirectos) ) { // MANTENIMIENTOS ASIGNADOS ?>
            <div class="col-lg-6 col-xs-12">
            <!-- small box -->
                <div class="small-box bg-info">
                    <div class="inner">
                        <center><h3>Mantenimientos asignados</h3></center>
                        <center><p>
                            <?php foreach($result as $value) {?>                                
                                <a href ="<?php echo Url::base(); ?>/index.php?r=cronogramas%2Fview&id=<?php echo $value['cronograma_id']?>" Target="_blank"><h6 class="btn btn-dark">Sucursal <?php echo $value['sucursal_nombre'].': '. $value['cuenta']?></h6></a>
                            <?php } ?>
                        </p></center>
                    </div>
                    <div class="icon">
                    <i class="fas fa-user-cog"></i>
                    </div>
                    <a href="<?php echo Url::base(); ?>/index.php?r=cronogramas%2Findex" class="small-box-footer">Ir al Módulo <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
        <?php } ?> 
        <?php if (in_array(4, $accesosDirectos)){  // REPORTES?> 
            <div class="col-lg-6 col-xs-12">
            <!-- small box -->
                <div class="small-box bg-warning">
                    <div class="inner">
                        <center><h3>Soportes</h3></center>
                        <center><p>
                        <h6 class="btn btn-dark">Realizados:  <?php echo $soporrealizados?></h6>
                        <h6 class="btn btn-dark">Pendientes:  <?php echo $soporpendientes?></h6>                           
                        </p></center>
                    </div>
                    <div class="icon">
                    <i class="fas fa-toolbox"></i>
                    </div>
                    <a href="<?php echo Url::base(); ?>/index.php?r=soportes%2Findex" class="small-box-footer">Ir al Módulo <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div> 
        <?php } ?>
    </div>

<!-- Load -->
<div class="modal fade" id="load" tabindex="-1" role="dialog" aria-labelledby="loadMeLabel">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
        <div class="modal-body text-center">
            <div class="loader">
                <!-- <img src="<?php echo Url::base(); ?>/images/loading.gif" alt=""> -->
            </div>
            <div clas="loader-txt">
            <p>Espere un momento por favor. <br><br><small>Se esta procesando la solicitud</small></p>
            </div>
        </div>
        </div>
    </div>
</div>



<!-- MODAL PARA REASIGNAR LA SUBACTIVIDAD -->
<div id="modalconsulta" class="modal fade" role="dialog"></div>

<!--  ========= Js ======== -->
<script>
$(document).on('click','.gestion',function(){      

 })         
</script>

views/site/login.php
<?php
    use yii\helpers\Html;
    use yii\helpers\Url;
    use yii\widgets\ActiveForm;
?>
    
<div class="container">
    <div class="card card-container">
        <!-- <img class="profile-img-card" src="//lh3.googleusercontent.com/-6V8xOA6M7BA/AAAAAAAAAAI/AAAAAAAAAAA/rzlHcD0KYwo/photo.jpg?sz=120" alt="" /> -->
        <!-- <img id="profile-img" class="" src="<?php echo Url::base(); ?>/images/img/StellarWayLogo.png" /> -->
        <center><b><h1>Kronos</h1></b></center>
        <p id="profile-name" class="profile-name-card"></p>
        <?php $form = ActiveForm::begin([
            'id' => 'login-form',
            'class'=> 'form-signin'
        ]); ?>
            <span id="reauth-email" class="reauth-email"></span>

            <?= $form->field($model, 'username')->textInput(['placeholder' => 'Usuario', 'class' => 'form-control'])->label(false) ?>        
            <?= $form->field($model, 'password')->passwordInput(['placeholder' => 'Contraseña', 'class' => 'form-control'])->label(false) ?>
                    
            <?= Html::submitButton('Iniciar Sesión', ['class' => 'btn btn-success btn-block text-bold', 'name' => 'login-button']) ?>
        <?php ActiveForm::end(); ?><!-- /form -->
    </div><!-- /card-container -->
</div><!-- /container -->

views/site/loginaut.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap4\ActiveForm;

?>

<?php $form = ActiveForm::begin([
    'id' => 'login-form',
]); ?>

    <?php if (isset($msg)) { ?>
        <div class="alert alert-danger" role="alert">
            <?php echo $msg; ?>
        </div>
    <?php } ?>
    
    <div class="row justify-content-md-center form-login">
        <div class="col-md-4 col-md-auto contentLogin">
            <center>
                <br>
                <img class="img-responsive" width="50%" src="<?php echo Url::base(); ?>/images/OSA.png">
                <br>
                <br>
            </center>
            <div class="col-lg-12">
                <div class="col-lg-12 noPadding">
                    <div class="form-group has-feedback">
                        <i class="icon-key"></i>
                        <?= $form->field($model, 'autoridad_code')->Input(['placeholder' => 'Codigo de Ingreso', 'class' => 'form-control'])->label(false) ?>
                    </div>
                </div>
                <div class="form-group col-lg-12 noPadding">
                        <br>
                        <div class="col-lg-12 noPadding ol-lg-offset-2">
                            <?= Html::submitButton('Ingresar a la Plataforma', ['class' => 'btn btn-success btn-block text-bold', 'name' => 'login-button']) ?>
                        </div>
                </div>
            </div>
             <br>
             <br>
            <center>
            <p>Siguenos en:</p>
            <a target="_blank" href="https://www.facebook.com/OrganizacionSaycoAcinpro/"><i class="fab fa-facebook fa-2x"></i></a>
            </center>
            
        </div>
    </div>

<?php ActiveForm::end(); ?>

views/site/loginindex.php
<?php
    use yii\helpers\Html;
    use yii\helpers\Url;
    use yii\bootstrap4\ActiveForm;
?>
<?php $form = ActiveForm::begin([
    'id' => 'login-form',
]); ?>

    <div class="row justify-content-md-center form-login">
        <div class="col-md-4 col-md-auto contentLogin">
            <center>
                <br>
                <img class="img-responsive" width="50%" src="<?php echo Url::base(); ?>/images/OSA.png">
                <br>
                <br>
            </center>
            <div class="col-lg-12">
                <div class="col-lg-12 noPadding">
                    <div class="form-group has-feedback">
                        <?= $form->field($model, 'username')->textInput(['placeholder' => 'Usuario', 'class' => 'form-control'])->label(false) ?>
                        <i class="fas fa-user user-icon"></i>
                    </div>
                </div>
                <div class="col-lg-12 noPadding">
                    <div class="form-group has-feedback">
                        <?= $form->field($model, 'password')->passwordInput(["data-toggle"=>"password",'placeholder' => 'Contraseña', 'class' => 'form-control'])->label(false) ?>
                        <i class="fas fa-key user-icon" ></i>
                    </div>
                </div>
                <div class="form-group col-lg-12 noPadding">
                        <br>
                        <div class="col-lg-12 noPadding ol-lg-offset-2">
                            <?= Html::submitButton('Iniciar Sesión', ['class' => 'btn btn-success btn-block text-bold', 'name' => 'login-button']) ?>
                        </div>
                </div>
            </div>
                <br>
            <center>
            <p>Siguenos en:</p>
            <a target="_blank" href="https://www.facebook.com/UniLibertadores/"><i class="fab fa-facebook fa-2x"></i></a>
            </center>
            
            <?= Html::a('<i class="fas fa-home"></i> Regresar al inicio', ['site/login'], ['class' => 'btn-sm btn-block btn btn-danger', 'style' => 'margin-top:10px;']) ?>
        </div>
    </div>
<?php ActiveForm::end(); ?>

views/site/newUser.php
<?php 
	use yii\helpers\Html;
	use yii\widgets\DetailView;
	use yii\helpers\Url;
?>

<div class="alert alert-<?php echo $alert ?>" role="alert">
  <span class="glyphicon glyphicon-<?php echo $graphicon;  ?>" aria-hidden="true"></span>
  <?php echo $msg; ?>
</div>
<?php if ($model) { ?>
	<div class="users-view">

	    <!-- <h1><?= Html::encode($this->title) ?></h1> -->
	    <div class="jumbotron">
	        <img width="150" src="<?php echo Url::base(); ?>/images/fotos/<?php echo $model->foto; ?>" alt="..." class="img-circle">
	        <p class="lead" style="color:#ffffff"><?php echo $model->nombres.' '.$model->apellidos; ?></p>
	    </div>

	    <!-- informacion personal -->
	    <div class="panel panel-primary">
	        <div class="panel-heading">Informacion personal</div>
	        <div class="panel-body">
	            <table class="table table-striped">
	                <tbody>
	                  <tr>
	                    <td><strong>Nombres: </strong><?php echo $model->nombres; ?></td>
	                    <td><strong>Apellidos: </strong><?php echo $model->apellidos; ?></td>
	                  </tr>
	                  <tr>
	                    <td><strong>Tipo de estado: </strong><?php echo $model->numeroIdentificacion; ?></td>
	                  </tr>
	                  <tr>
	                    <td><strong>Direccion: </strong><?php echo $model->direccion; ?></td>
	                    <td><strong>Telefono: </strong><?php echo $model->telefono; ?></td>
	                  </tr>
	                  <tr>
	                    <td colspan="2"><strong>Email: </strong><?php echo $model->email; ?></td>
	                  </tr>
	                </tbody>
	              </table>
	        </div>
	    </div>

	    <!-- informacion laboral -->
	    <div class="panel panel-primary">
	        <div class="panel-heading">Informacion laboral</div>
	        <div class="panel-body">
	            <table class="table table-striped">
	                <tbody>
	                  <tr>
	                    <td><strong>Username: </strong><?php echo $model->username; ?></td>
	                    <td><strong>Rol usuario: </strong><?php echo $model->rol->nombre; ?></td>
	                  </tr>
	                </tbody>
	              </table>
	        </div>
	    </div>
	    <p>
	        <?= Html::a('Actualizar informacion', ['users/update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
	        <?= Html::a('Registrar funcionario', ['site/register'], ['class' => 'btn btn-primary']) ?>
	        <?= Html::a('Volver', ['site/index'], ['class' => 'btn btn-primary']) ?>
	    </p> 
	</div>

<?php }else{ ?>
	<p>
	    <?= Html::a('Registrar funcionario', ['site/register'], ['class' => 'btn btn-primary']) ?>
	    <?= Html::a('Volver', ['site/index'], ['class' => 'btn btn-primary']) ?>
	</p> 
<?php } ?>

views/site/user.php
<h1>vista user normal</h1>
<?php echo 'asdfasdf'; ?>