models/Equipos.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "equipos".
 *
 * @property integer $equipo_id
 * @property string $equipo_identificacion_tecnologia
 * @property string $equipo_nombre_actual
 * @property integer $equipo_tipo_equipo_id
 * @property string $equipo_marca
 * @property string $equipo_ram
 * @property string $equipo_tipo_memoria_ram
 * @property string $equipo_cantidad_memoria_ram
 * @property string $equipo_marca_disco_duro
 * @property string $equipo_capacidad_disco_duro
 * @property string $equipo_procesador
 * @property string $equipo_velocidad_procesador
 * @property string $equipo_cantidad_nucleos_procesador
 * @property integer $equipo_systema_operativo_id
 * @property integer $equipo_office_id
 * @property string $equipo_pantalla
 * @property integer $equipo_sucursal_id
 * @property integer $equipo_usuario_id
 * @property integer $equipo_estado_id
 * @property string $equipo_numero_activo_contabilidad
 * @property string $equipo_fecha_ingreso
 * @property string $equipo_valor
 * @property string $equipo_observaciones
 * @property integer $equipo_area_id
 * @property integer $equipo_ip
 */
class Equipos extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'equipos';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['equipo_identificacion_tecnologia','equipo_nombre_actual','equipo_tipo_equipo_id','equipo_marca','equipo_modelo','equipo_capacidad_disco_duro','equipo_tipo_memoria_ram','equipo_marca_disco_duro','equipo_ram','equipo_procesador'],'required'],
            [['equipo_velocidad_procesador','equipo_velocidad_procesador','equipo_systema_operativo_id','equipo_office_id','equipo_sucursal_id','equipo_area_id','equipo_usuario_id','equipo_estado_id','equipo_observaciones'],'required'],
            [['equipo_tipo_equipo_id', 'equipo_systema_operativo_id', 'equipo_office_id', 'equipo_sucursal_id', 'equipo_usuario_id', 'equipo_estado_id', 'equipo_area_id'], 'integer'],
            [['equipo_fecha_ingreso', 'equipo_observaciones','equipo_id','equipo_ip'], 'safe'],
            [['equipo_identificacion_tecnologia', 'equipo_marca', 'equipo_ram'], 'string', 'max' => 100],
            [['equipo_nombre_actual', 'equipo_procesador', 'equipo_pantalla', 'equipo_numero_activo_contabilidad', 'equipo_valor', 'equipo_modelo'], 'string', 'max' => 255],
            [['equipo_tipo_memoria_ram',  'equipo_marca_disco_duro', 'equipo_capacidad_disco_duro', 'equipo_velocidad_procesador', 'equipo_cantidad_nucleos_procesador'], 'string', 'max' => 45],
            [['equipo_baja_activo'], 'file', 'skipOnEmpty' => true, 'extensions' => 'pdf'],
        ];
    }
    public function upload($name)
    {
        if($this->validate()){
            $this->equipo_baja_activo->saveAs('images/actas/'.$this->equipo_baja_activo->baseName.'.'.$this->equipo_baja_activo->extension);
            return true;            
        }else{
            return false;
        }
    }
    public function validacion()
    {
        if($this->equipo_baja_activo->extensions != ('pdf'))
        {
            echo "Archivos no validos";
        }
    }
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'equipo_id' => 'Equipo ID',
            'equipo_identificacion_tecnologia' => 'Identificacion T & T',
            'equipo_nombre_actual' => 'Nombre Actual',
            'equipo_tipo_equipo_id' => 'Tipo de Equipo',
            'equipo_marca' => 'Marca',
            'equipo_modelo' => 'Modelo',
            'equipo_ram' => 'Ram',
            'equipo_tipo_memoria_ram' => 'Tipo de Memoria Ram',
            'equipo_marca_disco_duro' => 'Marca de Disco Duro',
            'equipo_capacidad_disco_duro' => 'Capacidad de Disco Duro',
            'equipo_procesador' => 'Procesador',
            'equipo_velocidad_procesador' => 'Velocidad del Procesador',
            'equipo_cantidad_nucleos_procesador' => 'Nucleos del Procesador',
            'equipo_systema_operativo_id' => 'Sistema Operativo',
            'equipo_office_id' => 'Office',
            'equipo_pantalla' => 'Pantalla',
            'equipo_sucursal_id' => 'Sucursal',
            'equipo_area_id' => 'Area',
            'equipo_usuario_id' => 'Usuario',
            'equipo_estado_id' => 'Estado',
            'equipo_numero_activo_contabilidad' => 'Numero Activo Contabilidad',
            'equipo_fecha_ingreso' => 'Fecha Ingreso',
            'equipo_valor' => 'Valor',
            'equipo_observaciones' => 'Especificaciones adicionales',
            'equipo_ip'=>'Ip asignada'
        ];
    }

    public function getFuncionarios(){

        return $this->hasOne(Funcionarios::className(), ['funcionario_id' => 'equipo_usuario_id']);
    }

    public function getTipoMaquina(){

        return $this->hasOne(TiposDetalles::className(), ['tipo_detalle_id' => 'equipo_tipo_equipo_id' ]);
    }

    public function getSucursal(){

        return $this->hasOne(Sucursales::className(), ['sucursal_id' => 'equipo_sucursal_id']);
    }

    public function getArea(){

        return $this->hasOne(Areas::className(), ['area_id' => 'equipo_area_id']);
    }

    public function getEstado(){

        return $this->hasOne(TiposDetalles::className(), ['tipo_detalle_id' => 'equipo_estado_id'])
                            ->from(['t2' => TiposDetalles::tableName()]);
    }
    public function getLicencias(){

        return $this->hasOne(Licencias::classname(),['licencia_equipo_id' => 'equipo_id']);
    }
    public function getHistoricoLicencias(){

        return $this->hasOne(HistoricoLicencias::className(),['licencia_equipo_id' => 'equipo_id']);
    }
    public function getHistoricoEquipos(){

        return $this->hasOne(HistoricoEquipos::className(),['historico_equipo_id' => 'equipo_id']);
    }
    public function getMarca(){

        return $this->hasOne(TiposDetalles::className(),['tipo_detalle_id' =>'equipo_marca']);
    }
}

controllers/EquiposController.php
<?php
 
namespace app\controllers;

use Yii;
use app\models\Equipos;
use app\models\EquiposSearch;
use app\models\Licencias;
use app\models\HistoricoEquipos;
use app\models\HistoricoLicencias;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\db\Query;
use yii\web\UploadedFile;
use app\models\Areas;
use app\models\Sucursales;
use app\models\User;
use app\models\Users;
use app\models\Soporteequipos;
use app\models\Cronogramas;
use yii\filters\AccessControl;
use kartik\date\DatePicker;


/**
 * EquiposController implements the CRUD actions for Equipos model.
 */


require(__DIR__ . '/../vendor/phpqrcode/qrlib.php');


class EquiposController extends Controller
{
    // public function behaviors()
    // {
    //     return [
    //         'verbs' => [
    //             'class' => VerbFilter::className(),
    //             'actions' => [
    //                 'delete' => ['POST'],
    //             ],
    //         ],
    //     ];
    // }

      public function behaviors()
  {
      return [
          'access' => [
              'class' => AccessControl::className(),
              'only' => ['logout', 'user', 'admin','index','view','create','update'],
              'rules' => [
                  [
                      //El administrador tiene permisos sobre las siguientes acciones
                      'actions' => ['logout', 'admin','index','view','create','update'],
                      //Esta propiedad establece que tiene permisos
                      'allow' => true,
                      //Usuarios autenticados, el signo ? es para invitados
                      'roles' => ['@'],
                      //Este método nos permite crear un filtro sobre la identidad del usuario
                      //y así establecer si tiene permisos o no
                      'matchCallback' => function ($rule, $action) {
                          //Llamada al método que comprueba si es un administrador
                          return User::isUserAdmin(Yii::$app->user->identity->id);
                      },
                  ],
                  [
                     //Los usuarios de recaudo tienen permisos sobre las siguientes acciones
                     'actions' => ['logout', 'user','index','view','create','update'],
                     //Esta propiedad establece que tiene permisos
                     'allow' => true,
                     //Usuarios autenticados, el signo ? es para invitados
                     'roles' => ['@'],
                     //Este método nos permite crear un filtro sobre la identidad del usuario
                     //y así establecer si tiene permisos o no
                     'matchCallback' => function ($rule, $action) {
                        //Llamada al método que comprueba si es un usuario de recaudo
                        return User::isUserLinalca(Yii::$app->user->identity->id);
                    },
                  ],
              ],
          ],
           //Controla el modo en que se accede a las acciones, en este ejemplo a la acción logout
           //sólo se puede acceder a través del método post
          'verbs' => [
              'class' => VerbFilter::className(),
              'actions' => [
                  'logout' => ['post'],
              ],
          ],
      ];
  }

    /**
     * Lists all Equipos models.
     * @return mixed
         */
    public function actionIndex()
    { 
        $model = Equipos::find()->All();
        $searchModel = new EquiposSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'model' => $model,
        ]);
    }

    /**
     * Displays a single Equipos model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        

        // se instancia la Clase Query.
        $query = new Query();
        $connection = Yii::$app->db;

        // consulta que muestra la informacion en el index del modulo de Visita
        $query = $connection->createCommand('SELECT     *,
                                                        (select tipo_detalle_nombre from tipos_detalles where tipo_detalle_id = equipo_tipo_equipo_id) as TipoE,
                                                        (select tipo_detalle_nombre from tipos_detalles where tipo_detalle_id = equipo_systema_operativo_id) as sistemaO,
                                                        (select tipo_detalle_nombre from tipos_detalles where tipo_detalle_id = equipo_office_id) as office,
                                                        (select tipo_detalle_nombre from tipos_detalles where tipo_detalle_id = equipo_estado_id) as estado,
                                                        (select tipo_detalle_nombre from tipos_detalles where tipo_detalle_id = equipo_procesador) as procesador,
                                                        (select tipo_detalle_nombre from tipos_detalles where tipo_detalle_id = equipo_ram) as ram,
                                                        (select tipo_detalle_nombre from tipos_detalles where tipo_detalle_id = equipo_capacidad_disco_duro) as capacidad_disk_duro,
                                                        (select tipo_detalle_nombre from tipos_detalles where tipo_detalle_id = equipo_marca) as equipo_marca,
                                                        (select tipo_detalle_nombre from tipos_detalles where tipo_detalle_id = equipo_tipo_memoria_ram) as tipo_memoria_ram
                                                from    equipos 
                                                        join funcionarios on (equipo_usuario_id = funcionario_id)
                                                        join sucursales on (equipo_sucursal_id = sucursal_id)
                                                        join areas on (equipo_area_id = area_id)
                                                where   1=1
                                                        and equipo_id ='.$id
                                                );
        $result = $query->queryAll();


        $query = $connection->createCommand('SELECT     *,
                                                        (select tipo_detalle_nombre from tipos_detalles where tipo_detalle_id = licencia_tipo_licencia_id) as producto, 
                                                        (select tipo_detalle_nombre from tipos_detalles where tipo_detalle_id=licencia_version) as licencia_versiones,
                                                        (select     tipo_nombre 
                                                            from    tipos_detalles 
                                                                    join tipos on (tipo_detalle_tipo_id = tipo_id)
                                                            where   tipo_detalle_id = licencia_tipo_licencia_id) as tipo
                                                from    licencias                                                         
                                                where   1=1
                                                        and licencia_equipo_id ='.$id
                                                );
        $licencias = $query->queryAll();        

        $query = $connection->createCommand("SELECT     *,
                                                        (select CONCAT(nombres,' ',apellidos) from users where id = cronograma_quien_realiza ) as quienRealiza,
                                                        case when cronograma_detalle_realizado = 0 then 'Pendiente'
                                                             when cronograma_detalle_realizado = 1 then 'Realizado' end as estado, 
                                                        case when cronograma_detalle_aprobado = 2 then 'NO  por: '
                                                             when cronograma_detalle_aprobado = 1 then 'SI  por: ' end as aprobado, 
                                                        (select  funcionario_nombres from funcionarios where funcionario_id = cronograma_detalle_quien_aprueba) as quienAprueba

                                                from    cronogramas_detalles 
                                                        join cronogramas on (cronograma_detalle_cronograma_id = cronograma_id)                                                        
                                                where   1=1
                                                         
                                                        -- and cronograma_detalle_realizado = 0
                                                        and cronograma_detalle_equipo_id =".$id
                                                );
        $cronogramas = $query->queryAll();

        $query = $connection->createCommand('SELECT     *,
                                                        (select tipo_detalle_nombre from tipos_detalles where tipo_detalle_id = licencia_tipo_licencia_id) as producto, 
                                                        (select     tipo_nombre 
                                                            from    tipos_detalles 
                                                                    join tipos on (tipo_detalle_tipo_id = tipo_id)
                                                            where   tipo_detalle_id = licencia_tipo_licencia_id) as tipo
                                                from    historico_licencias                                                         
                                                where   1=1
                                                        and licencia_equipo_id ='.$id
                                                );

views/equipos/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\EquiposSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="equipos-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'equipo_id') ?>

    <?= $form->field($model, 'equipo_identificacion_tecnologia') ?>

    <?= $form->field($model, 'equipo_nombre_actual') ?>

    <?= $form->field($model, 'equipo_tipo_equipo_id') ?>

    <?= $form->field($model, 'equipo_marca') ?>

    <?php // echo $form->field($model, 'equipo_ram') ?>

    <?php // echo $form->field($model, 'equipo_tipo_memoria_ram') ?>

    <?php // echo $form->field($model, 'equipo_cantidad_memoria_ram') ?>

    <?php // echo $form->field($model, 'equipo_marca_disco_duro') ?>

    <?php // echo $form->field($model, 'equipo_capacidad_disco_duro') ?>

    <?php // echo $form->field($model, 'equipo_procesador') ?>

    <?php // echo $form->field($model, 'equipo_velocidad_procesador') ?>

    <?php // echo $form->field($model, 'equipo_cantidad_nucleos_procesador') ?>

    <?php // echo $form->field($model, 'equipo_systema_operativo_id') ?>

    <?php // echo $form->field($model, 'equipo_office_id') ?>

    <?php // echo $form->field($model, 'equipo_pantalla') ?>

    <?php // echo $form->field($model, 'equipo_sucursal_id') ?>

    <?php // echo $form->field($model, 'equipo_usuario_id') ?>

    <?php // echo $form->field($model, 'equipo_estado_id') ?>

    <?php // echo $form->field($model, 'equipo_numero_activo_contabilidad') ?>

    <?php // echo $form->field($model, 'equipo_fecha_ingreso') ?>

    <?php // echo $form->field($model, 'equipo_valor') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/equipos/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Equipos */

$this->title = 'Registro de Equipo';
$this->params['breadcrumbs'][] = ['label' => 'Equipos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="equipos-create">

   

    <!-- <div class="alert alert-success" role="alert"> <h3><?= Html::encode($this->title) ?></h3></div> -->



    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>


</div>

views/equipos/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

$this->title = 'Equipos registrados';
$this->params['breadcrumbs'][] = $this->title;
?>
    
<div class="card card-purple">
    <div class="card-header">
    <!-- <h3 class="card-title">DataTable with default features</h3> -->Resultados encontrados
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <p>
            <?= Html::a('Registrar Equipo', ['equipos/create'], ['class' => 'btn btn-success']) ?>
        </p>
        <div class="col-lg-12">
            <div class="row">
             <div class="table-responsive">              
                <table id="example1" class="table table-bordered table-hover table-striped">
                    <thead>
                    <tr>
                    <th>Identificación tecnologia</th>
                    <th>Nombre actual</th>
                    <th>Tipo de Equipo</th>
                    <th>equipo_marca</th>
                    <th>Sucursal</th>
                    <th>Funcionario</th>
                    <th>Estado</th>
                    <th>No. Activo</th>
                    <th>Acciones</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($model as $key => $value) { ?>
                    <tr>
                        <td><?php echo $value['equipo_identificacion_tecnologia'] ?></td>
                        <td><?php echo $value['equipo_nombre_actual'] ?></td>
                        <td><?php echo $value->tipoMaquina->tipo_detalle_nombre ?></td>
                        <td><?php echo $value->marca->tipo_detalle_nombre?></td>                        
                        <td><?php echo $value->sucursal['sucursal_nombre'] ?></td>
                        <td><?php echo $value->funcionarios['funcionario_nombres']?></td>
                        <td><?php echo $value->estado->tipo_detalle_nombre?></td>
                        <td><?php echo $value->equipo_numero_activo_contabilidad?></td>
                        <td>
                            <?= Html::a('Ver', ['equipos/view', 'id'=> $value['equipo_id']], ['class' => 'btn btn-primary btn-block ']) ?>
                            <?= Html::a('Actualizar', ['equipos/update', 'id'=> $value['equipo_id']], ['class' => 'btn btn-warning btn-block ']) ?>
                        </td>
                    </tr>
                    <?php } ?>
                    </tbody>
                </table>
              </div>  
            </div>
        </div>    
    </div>
    <!-- /.card-body -->
</div>
<script>
  $(function () {
    $("#example1").DataTable({
      "language": {
          "sProcessing":    "Procesando...",
          "sLengthMenu":    "Mostrar _MENU_ registros",
          "sZeroRecords":   "No se encontraron resultados",
          "sEmptyTable":    "Ningún dato disponible en esta tabla",
          "sInfo":          "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
          "sInfoEmpty":     "Mostrando registros del 0 al 0 de un total de 0 registros",
          "sInfoFiltered":  "(filtrado de un total de _MAX_ registros)",
          "sInfoPostFix":   "",
          "sSearch":        "Buscar:",
          "sUrl":           "",
          "sInfoThousands":  ",",
          "sLoadingRecords": "Cargando...",
          "oPaginate": {
              "sFirst":    "Primero",
              "sLast":    "Último",
              "sNext":    "Siguiente",
              "sPrevious": "Anterior"
          },
          "oAria": {
              "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
              "sSortDescending": ": Activar para ordenar la columna de manera descendente"
          }
      },
      "responsive": true, "lengthChange": false, "autoWidth": false,
      "buttons": ["copy", "csv", "excel"]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');


    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
</script>

views/equipos/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Equipos */

$this->title = 'Actualización de Equipo: ' . ' ' . $model->equipo_identificacion_tecnologia;
$this->params['breadcrumbs'][] = ['label' => 'Equipos', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->equipo_id, 'url' => ['view', 'id' => $model->equipo_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="equipos-update">
    <div class="alert alert-light" role="alert"> <h3><?= Html::encode($this->title) ?></h3></div>
    <?= $this->render('formupdate', [
        'model' => $model,
    ]) ?>
</div>