models/CheckList.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "check_list".
 *
 * @property integer $check_list_id
 * @property integer $check_list_cronograma_id
 * @property integer $check_list_equipo_id
 * @property integer $check_list_usuario_registra
 * @property string $check_list_fecha_registro
 * @property integer $check_list_usuario_confirma
 * @property integer $check_list_campo_id
 * @property string $check_list_valor
 */
class CheckList extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'check_list';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['check_list_cronograma_id', 'check_list_equipo_id', 'check_list_usuario_registra', 'check_list_usuario_confirma', 'check_list_campo_id'], 'integer'],
            [['check_list_fecha_registro', 'file'], 'safe'],
            [['check_list_valor'], 'string', 'max' => 255],
                 [ 'file', 'file', 
                   'skipOnEmpty' => true,
                   'uploadRequired' => 'No has seleccionado ningún archivo', //Error
                   // 'maxSize' => 1024*1024*1, //1 MB
                   // 'tooBig' => 'El tamaño máximo permitido es 1MB', //Error
                   'extensions' => 'jpg',
                   'wrongExtension' => 'El archivo {file} no contiene una extensión permitida {extensions}', //Error
                   'maxFiles' => 60,
                   // 'tooMany' => 'El máximo de archivos permitidos son {limit}', //Error
               ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'check_list_id' => 'Check List ID',
            'check_list_cronograma_id' => 'Check List Cronograma ID',
            'check_list_equipo_id' => 'Check List Equipo ID',
            'check_list_usuario_registra' => 'Check List Usuario Registra',
            'check_list_fecha_registro' => 'Check List Fecha Registro',
            'check_list_usuario_confirma' => 'Check List Usuario Confirma',
            'check_list_campo_id' => 'Check List Campo ID',
            'check_list_valor' => 'Check List Valor',
        ];
    }
}

controllers/CheckListController.php
<?php

namespace app\controllers;

use Yii;
use app\models\CheckList;
use app\models\CheckListSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\db\Query;
use yii\web\UploadedFile;
use app\models\Areas;
use kartik\date\DatePicker;

/**
 * CheckListController implements the CRUD actions for CheckList model.
 */
class CheckListController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all CheckList models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CheckListSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single CheckList model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        // echo "<pre>";
        // print_r($_REQUEST);die();

        $model = CheckList::findOne($id);

        $query = new Query();
        $connection = Yii::$app->db;
        $idUsuario = yii::$app->user->identity->id;

        $query = $connection->createCommand("SELECT     *,
                                                        (select CONCAT(nombres,' ',apellidos) from users where id = cronograma_quien_realiza ) as quienRealiza,
                                                        (select tipo_detalle_nombre from tipos_detalles where tipo_detalle_id = cronograma_tipo_mantenimiento) as tipoMantenimiento, 
                                                        case when cronograma_detalle_aprobado = 0 then 'Pendiente por Aprobar'
                                                             when cronograma_detalle_aprobado = 1 then 'Aprobado' end as estado, 
                                                        ( select check_list_fecha_registro from check_list where check_list_cronograma_id = ".$id." and check_list_equipo_id = ".$_REQUEST['Equipo']." order by 1 desc limit 1 )  as fechaRegistro
                                                from    cronogramas_detalles 
                                                        join cronogramas on (cronograma_detalle_cronograma_id = cronograma_id)
                                                        join equipos on (cronograma_detalle_equipo_id = equipo_id)
                                                where   1=1
                                                        and equipo_id = ".$_REQUEST['Equipo']."
                                                        and cronograma_detalle_id =".$id."
                                                         ");
        $cronogramas = $query->queryAll();
        
        $query = $connection->createCommand("SELECT     *

                                                from    check_list
                                                        join campos_check_list on (check_list_campo_id = campo_check_list_id) 
                                                where   1=1
                                                        and check_list_equipo_id = ".$_REQUEST['Equipo']."
                                                        ");
        $campos = $query->queryAll();    

        $query = $connection->createCommand("SELECT *
                                            from    cronograma_detalle_imagenes
                                            where   1=1
                                                    and cronograma_detalle_imagen_equipo_id =".$_REQUEST['Equipo']."
                                                    and cronograma_detalle_imagen_detalle_id=".$_REQUEST['id']."");
        $imagenes = $query->queryAll();

        // echo "<pre>";
        // print_r($cronogramas);
        // // print_r($campos);
        // die();

        return $this->render('view', [
            'cronogramas' => $cronogramas,
            'campos' => $campos,
            'imagenes' => $imagenes,
            'model' => $model,
        ]);
    }

    /**
     * Creates a new CheckList model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new CheckList();

        // echo "<pre>";
        // print_r($_REQUEST);die();
        // se instancia la Clase Query.
        $query = new Query();
        $connection = Yii::$app->db;
        $idUsuario = yii::$app->user->identity->id;

        $query = $connection->createCommand("SELECT     *,
                                                        (select CONCAT(nombres,' ',apellidos) from users where id = cronograma_quien_realiza ) as quienRealiza
                                                from    cronogramas_detalles 
                                                        join cronogramas on (cronograma_detalle_cronograma_id = cronograma_id)
                                                        join equipos on (cronograma_detalle_equipo_id = equipo_id)
                                                where   1=1
                                                        and cronograma_realizado = 0 
                                                        and equipo_id =".$_REQUEST['id']."
                                                        and cronograma_id=".$_REQUEST['cronograma']."");
        $cronogramas = $query->queryAll();
        
        $query = $connection->createCommand("SELECT     *
                                                from    campos_check_list 
                                                where   1=1
                                                        ");
        $campos = $query->queryAll();    
        // echo "<pre>";
        // print_r($campos);die();



        if (Yii::$app->request->post() ) {

            // echo "<pre>";
            // print_r($_REQUEST);die();

            $model->file = UploadedFile::getInstances($model, 'file');

            // print_r($model->file);

            // // die();
            // die();

            // echo "<pre>";
            // print_r($_REQUEST);die();
            foreach ($_REQUEST['Valores'][8] as $key => $value) {
                
                // INSERCION EN LA TABLA CRONOGRA
                $sql = $connection -> createCommand ()-> insert ( 'check_list' , 
                                                        [ 
                                                         'check_list_cronograma_id' => $_REQUEST['cronograma'],
                                                         'check_list_equipo_id' => $_REQUEST['id'],
                                                         'check_list_usuario_registra' => $idUsuario,
                                                         'check_list_fecha_registro' => date('Y-m-d H:i:s'),
                                                         'check_list_campo_id' => $key,
                                                         'check_list_valor' => strtoupper($value),
                                                        ]
                                                        )-> execute ();
                // $idCronograma = Yii::$app->db->getLastInsertID();


            }

            if ($model->file) {
                $contador=0;
                foreach ($model->file as $file) {
                    $file->saveAs('mantenimientos/' . $_REQUEST['cronograma'].$_REQUEST['id'].$contador.'.' . $file->extension);

                    $sql = $connection -> createCommand ()-> insert ( 'cronograma_detalle_imagenes' , 
                                                [ 
                                                    'cronograma_detalle_imagen_detalle_id' => $_REQUEST['cronograma'],
                                                    'cronograma_detalle_imagen_ruta' => 'mantenimientos/' . $_REQUEST['cronograma'].$_REQUEST['id'].$contador.'.' . $file->extension,
                                                    'cronograma_detalle_imagen_equipo_id' => $_REQUEST['id'].'.' . $file->extension,
                                                ]
                                                )-> execute ();

                $contador++;    
                }
            }

            $query = $connection->createCommand("UPDATE cronogramas_detalles 
                                            SET     cronograma_detalle_aprobado=0,
                                                    cronograma_detalle_realizado = 1, 
                                                    cronograma_tiempo_final_utilizado='".$_REQUEST['TiempoFinal']."'
                                            where   1=1
                                                    and cronograma_detalle_id =".$_REQUEST['cronograma']."");
            $validado = $query->execute();

            
            return $this->redirect(['confirma', 'Equipo' => $_REQUEST['id'], 'cronograma' => $_REQUEST['cronograma'] ]);

        } else {
            
            return $this->render('create', [
                'model' => $model,
                'cronogramas'=>$cronogramas,
                'campos'=>$campos,
            ]);
        }
    }

    /**
     * Updates an existing CheckList model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate()
    {
        
        // echo "<pre>";
        // print_r($_REQUEST);
        // die();

        $query = new Query();
        $connection = Yii::$app->db;
        $idUsuario = yii::$app->user->identity->id;

        $query = $connection->createCommand("SELECT     *,

views/check-list/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\CheckListSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="check-list-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'check_list_id') ?>

    <?= $form->field($model, 'check_list_cronograma_id') ?>

    <?= $form->field($model, 'check_list_equipo_id') ?>

    <?= $form->field($model, 'check_list_usuario_registra') ?>

    <?= $form->field($model, 'check_list_fecha_registro') ?>

    <?php // echo $form->field($model, 'check_list_usuario_confirma') ?>

    <?php // echo $form->field($model, 'check_list_campo_id') ?>

    <?php // echo $form->field($model, 'check_list_valor') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/check-list/confirmacion.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\ActiveForm;
/* @var $this yii\web\View */
/* @var $model app\models\CheckList */

$this->title = 'Confirmacion del Mantenimiento';
$this->params['breadcrumbs'][] = ['label' => 'Equipos Asignados', 'url' => ['/cronogramas/lista', 'id'=>$cronogramas[0]['cronograma_detalle_cronograma_id'] ]];
$this->params['breadcrumbs'][] = $this->title;

// echo "<pre>";
// print_r($cronogramas);die();

?>
<div class="check-list-view">

    
<div class="card card-info">
    <div class="card-header">Mantenimiento Registrado</div>
    <div class="card-body">
    
        <div class="card card-info">
            <div class="card-header">Informacion General</div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <tr>
                            <td><b>Identificacion T & T</b></td>
                            <td><b>Nombre Actulal</b></td>
                            <td><b>Tipo de Mantenimiento</b></td>
                            <td><b>Quien lo realiza</b></td>
                            <td><b>Hora del Mantenimiento</b></td>
                            <td><b>Tiempo utilizado(H:m:s)</b></td>
                        </tr>    
                        <tr>
                            <td><?php echo $cronogramas[0]['equipo_identificacion_tecnologia'] ?></td>
                            <td><?php echo $cronogramas[0]['equipo_nombre_actual'] ?></td>
                            <td><?php echo $cronogramas[0]['tipoMantenimiento'] ?></td>
                            <td><?php echo $cronogramas[0]['quienRealiza'] ?></td>
                            <td><?php echo $cronogramas[0]['cronograma_detalle_hora_inicio']." a ".$cronogramas[0]['cronograma_detalle_hora_fin'] ?></td>
                            <td><?php echo $cronogramas[0]['cronograma_tiempo_final_utilizado'] ?></td>

                        </tr>
                    </table>  
                </div>
            </div>
        </div>

        <div class="card card-success">
            <div class="card-header">Informacion Del Mantenimiento para aprobar</div>
            <div class="card-body">
                <div class="col-lg-12">
                    <div class="card card-info">
                        <div class="card-header">Imagenes del Mantenimiento</div>
                        <div class="card-body">
                            <?php 
                                    $contador=0;
                                    foreach ($imagenes as $keyI => $valueI) { 

                                        ?>

                                    <div class="col-lg-12 ">
                                        <?php echo Html::img("@web/".$valueI['cronograma_detalle_imagen_ruta']."", ["width"=>"300px" , "height" => "200px"]) ?>
                                    </div>
                                <?php 
                                    $contador++;
                                    } ?>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <?php foreach ($checklist as $keyC => $valueC) { ?>
                    
                <div class="col-lg-12 form-group">
                    <div class="alert alert-info pop"  role="alert"  data-toggle="popover" data-placement="top" title="Instruccion de Labor" data-content="<?php echo $valueC['campo_check_list_popover_valor'] ?>">
                        <?php echo $valueC['campo_check_list_nombre'] ?> : 
                        <?php echo strtoupper($valueC['check_list_valor']);  ?>
                    </div>
                </div>    
                <?php } ?>
                
                
                </div>
                <div class="col-lg-12">
                    <div class="col-lg-12">
                    <?= Html::a('ACTUALIZAR LA INFORMACIÓN', ['check-list/update', 'cronograma'=>$cronogramas[0]['cronograma_detalle_id'],'Equipo'=>$cronogramas[0]['cronograma_detalle_equipo_id']], ['class' => 'btn btn-danger btn-block']) ?>
                </div>
                <div class="col-lg-12">
                    <button class="btn btn-success btn-block" id="confirmation" data-toggle="modal" data-target="#myModal">CONFIRMAR EL MANTENIMIENTO</button>
                </div>
                </div>
            </div>
        </div>


    </div>
</div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Confirmación de Mantenimiento</h4>
      </div>
      <?php $form = ActiveForm::begin([
                "method" => "post",
                "options" => ["enctype" => "multipart/form-data"],
                "action" => ["aprobacion"]
            ]); ?>
      <input type="hidden" name="cronograma" value="<?php echo$cronogramas[0]['cronograma_detalle_id'] ?>"> 
      <input type="hidden" name="equipo" value="<?php echo $cronogramas[0]['cronograma_detalle_equipo_id'] ?>"> 
      <div class="modal-body">
        <label for="">Quien Aprueba</label>
        <input type="text" name="aprueba" class="form-control">
        <label for="">Observaciones</label>
        <input type="text" name="observacion" class="form-control">
        <!-- firma digital -->
        <div class="row">                 
            <div class="col-lg-12 col-xs-12 form-group" id="contentFirmaDigital">
            <label for="">Firma Digital</label>
                <div id="signArea" >
                    <canvas class="sign-pad" id="sign-pad" style="border: 1px solid black" height="100"></canvas>
                </div>
                <button class="btn btn-success" type="button" id="btnSaveSign">Guardar Firma</button>
                <button class="btn btn-danger" type="button" id="btnClearSign">Limpiar</button>
                <input type="hidden" name="Visitas[firmadigital]" id="inputfirma" value="1">
            </div>
            <div class="col-lg-12 col-xs-12 form-group">
                <img src="" class="hide" id="imageFirma"> <br>
                <!-- <button class="btn btn-primary hide" type="button" id="btnNewSign">Nueva firma</button> -->
            </div>
        </div>
        <!-- /firma digital -->

      </div>
      
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">cerrar</button>
        <button type="submit" class="btn btn-primary" id="validarCodigo">Aprobar Mantenimiento</button>
        <!-- <input type="submit" class="btn btn-primary">Aprobar Mantenimiento -->
      </div>
      <?php ActiveForm::end(); ?>
    </div>
  </div>
</div>

<script>
        
    $('.pop').click(function(event) {
        $('[data-toggle="popover"]').popover('hide');
        $(this).popover('show');
    });


    // FIRMA DIGITAL 
    $("#btnClearSign").click(function(e){
            $('#signArea').signaturePad().clearCanvas();
    });
            
    $("#btnSaveSign").click(function(e){
        html2canvas([document.getElementById('sign-pad')], {
            onrendered: function (canvas) {
                var canvas_img_data = canvas.toDataURL('image/png');
                var data = canvas_img_data.replace(/^data:image\/(png|jpg);base64,/, "");
                //ajax call to save image inside folder
                $.ajax({
                    url: '<?php echo Yii::$app->request->baseUrl ?>/?r=check-list/guardarfirmadigitalindependiente',
                    data: { 
                        data:data, 
                        idproducto : <?php echo $cronogramas[0]['cronograma_detalle_id'] ?>,
                        equipo : <?php echo $cronogramas[0]['cronograma_detalle_equipo_id'] ?>,

                    },
                    type: 'POST',
                    success: function (file_name) {
                        // window.location.reload();
                        $('#imageFirma').addClass('hide');
                        $('#imageFirma').attr('src','');
                        $('#imageFirma').attr('src',file_name);
                        $('#imageFirma').removeClass('hide');
                        $('#btnNewSign').removeClass('hide');
                        
                        $('#contentFirmaDigital').addClass('hide');
                    }
                });
            }
        });
    });

    $("#btnNewSign").click(function(e){
        $('#imageFirma').addClass('hide');
        $('#imageFirma').attr('src','');
        $('#btnNewSign').addClass('hide');
        $('#signArea').signaturePad().clearCanvas();
        $('#contentFirmaDigital').removeClass('hide');
    });

    $('#btn-aprobado').click(function(event) {

        $.ajax({
                url: '<?php echo Yii::$app->request->baseUrl ?>/?r=check-list/aprobacion',
                type: 'get',
                data: {
                    id : $(this).data("id"),
                    cronograma : $(this).data("cronograma"),
                },
                success: function (data) {
                    <?php $arrayParams = [ 'id'=>$cronogramas[0]['cronograma_detalle_id'], 'Equipo'=> $cronogramas[0]['cronograma_detalle_equipo_id'] ];
                                              $params = array_merge(["check-list/view"], $arrayParams);
                                              $url = Yii::$app->urlManager->createUrl($params); ?>

                    location.href = "<?php echo $url; ?>";
                }
            }); // fin ajax
    });    
</script>

views/check-list/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\CheckList */

$this->title = 'Create Check List';
$this->params['breadcrumbs'][] = ['label' => 'Check Lists', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="check-list-create">

    <!-- <h1><?= Html::encode($this->title) ?></h1> -->

    <?= $this->render('_form', [
        'model' => $model,
        'cronogramas'=>$cronogramas,
        'campos'=>$campos,
    ]) ?>

</div>

views/check-list/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\CheckListSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Check Lists';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="check-list-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Check List', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'check_list_id',
            'check_list_cronograma_id',
            'check_list_equipo_id',
            'check_list_usuario_registra',
            'check_list_fecha_registro',
            // 'check_list_usuario_confirma',
            // 'check_list_campo_id',
            // 'check_list_valor',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>

views/check-list/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\CheckList */

$this->title = "Mantenimiento Registrado";
$this->params['breadcrumbs'][] = ['label' => 'Equipos Asignados', 'url' => ['/cronogramas/lista', 'id'=>$cronogramas[0]['cronograma_detalle_cronograma_id'] ]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="check-list-view">

    

    <div class="card card-primary">
    <div class="card-header"><h1><?= Html::encode($this->title) ?></h1></div>
    <div class="">
    
        <div class="card card-info">
            <div class="card-header">Informacion General</div>
            <div class="">
                <div class="table-responsive">
                    <table class="table">
                        <tr>
                            <td><b>Identificacion T & T</b></td>
                            <td><b>Nombre Actulal</b></td>
                            <td><b>Tipo de Mantenimiento</b></td>
                            <td><b>Quien lo realiza</b></td>
                            <td><b>Hora del Mantenimiento</b></td>
                            <td><b>Estado</b></td>
                            <td><b>Tiempo utilizado(H:m:s)</b></td>
                            <td><b>Fecha</b></td>
                        </tr>    
                        <tr>
                            <td><?php echo $cronogramas[0]['equipo_identificacion_tecnologia'] ?></td>
                            <td><?php echo $cronogramas[0]['equipo_nombre_actual'] ?></td>
                            <td><?php echo $cronogramas[0]['tipoMantenimiento'] ?></td>
                            <td><?php echo $cronogramas[0]['quienRealiza'] ?></td>
                            <td><?php echo $cronogramas[0]['cronograma_detalle_hora_inicio']." a ".$cronogramas[0]['cronograma_detalle_hora_fin'] ?></td>
                            <td><?php echo $cronogramas[0]['estado'] ?></td>
                            <td><?php echo $cronogramas[0]['cronograma_tiempo_final_utilizado'] ?></td>
                            <td><?php echo $cronogramas[0]['fechaRegistro'] ?></td>
                        </tr>
                    </table>  
                </div>

                <?php if($cronogramas[0]['cronograma_detalle_aprobado']==1){ ?>
                <div class="col-lg-12">
                    <div class="card card-primary">                        
                        <div class="card-header"><h6>Firma de Aprobación</h6></div> 
                          <div class="table-responsive">                       
                            <table class="table table-bordered table-hover">                            
                                <tr>
                                    <td><b>Quien Autoriza</b></td>
                                    <td><b>Observación</b></td>
                                    <td><b>Firma Digital</b></td>
                                </tr>    
                                <tr>
                                    <td><?php echo $cronogramas[0]['cronograma_detalle_quien_aprueba'] ?></td>
                                    <td><?php echo $cronogramas[0]['cronograma_detalle_observacion_usuario'] ?></td>
                                    <td><?php echo Html::img("@web/images/firmasdigitales/mantenimiento_".$cronogramas[0]['cronograma_detalle_id']."_".$cronogramas[0]['cronograma_detalle_equipo_id'].".png") ?></td>
                                </tr>
                            </table>  
                         </div>   
                        </div>
                    </div>
                </div>
                <?php } ?>
            </div>
        </div>
        <div class="card card-success">
            <div class="card-header">Informacion Del Mantenimiento registrado</div>
            <div class="">
                <div class="col-lg-12">
                    <div class="card card-info">
                        <div class="card-header">Imagenes del Mantenimiento</div>
                        <div class="form-row">
                            <?php 
                                    $contador=0;
                                    foreach ($imagenes as $keyI => $valueI) { 

                                        ?>
                                    
                                    <div class="col-lg-6">
                                        <?php echo Html::img("@web/".$valueI['cronograma_detalle_imagen_ruta']."", ["class"=>"img-fluid"]) ?>
                                    </div>                                                                            
                                <?php 
                                    $contador++;
                                    } ?>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <?php foreach ($campos as $keyC => $valueC) { ?>
                    
                <div class="col-lg-12 form-group">
                    <div class="alert alert-info pop"  role="alert"  data-toggle="popover" data-placement="top" title="Instruccion de Labor" data-content="<?php echo $valueC['campo_check_list_popover_valor'] ?>">
                        <?php echo $valueC['campo_check_list_nombre'] ?> : 
                        <?php echo strtoupper($valueC['check_list_valor']);  ?>
                    </div>
                </div>    
                <?php } ?>
                </div>
            </div>
        </div>
        <?php if ($cronogramas[0]['cronograma_detalle_aprobado']==0) { ?>
            <?= Html::a('Aprobar', ['check-list/confirma', 'cronograma'=>$cronogramas[0]['cronograma_detalle_id'],'Equipo'=>$cronogramas[0]['cronograma_detalle_equipo_id']], ['class' => 'btn btn-primary']) ?>
            <?= Html::a('Actualizar Información', ['check-list/update', 'cronograma'=>$cronogramas[0]['cronograma_detalle_id'],'Equipo'=>$cronogramas[0]['cronograma_detalle_equipo_id']], ['class' => 'btn btn-success']) ?>
        <?php } ?>
        <?= Html::a('Regresar a la Maquina', ['equipos/view', 'id'=>$cronogramas[0]['cronograma_detalle_equipo_id']], ['class' => 'btn btn-danger']) ?>
    </div>
</div>
</div>
<script>
        $('.pop').click(function(event) {
        $('[data-toggle="popover"]').popover('hide');
        $(this).popover('show');
    });
</script>