models/Licencias.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "licencias".
 *
 * @property integer $licencia_id
 * @property integer $licencia_equipo_id
 * @property integer $licencia_tipo_licencia_id
 * @property string $licencia_numero
 * @property string $licencia_version
 * @property string $licencia_especificaciones
 * @property integer $licencia_estado_id
 * @property integer $licencia_sucursal_id
 * @property string $licencia_identificacion_tecnologia
 */
class Licencias extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'licencias';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['licencia_sucursal_id','licencia_tipo_licencia_id','licencia_numero','licencia_identificacion_tecnologia','licencia_especificaciones','licencia_version'],'required'],
            [['licencia_equipo_id', 'licencia_tipo_licencia_id', 'licencia_estado_id', 'licencia_sucursal_id'], 'integer'],
            [['licencia_especificaciones'], 'string'],
            [['licencia_numero','licencia_identificacion_tecnologia'], 'string', 'max' => 255],
            [['licencia_version'], 'string', 'max' => 100],
        ];
    }
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'licencia_id' => 'Licencia ID',
            'licencia_equipo_id' => 'Licencia Equipo ID',
            'licencia_tipo_licencia_id' => 'Licencia Tipo Licencia ID',
            'licencia_numero' => 'Clave del Producto',
            'licencia_version' => 'Version',
            'licencia_especificaciones' => 'Especificaciones Adicionales',
            'licencia_estado_id' => 'Licencia Estado ID',
            'licencia_sucursal_id' => 'Licencia Sucursal ID',
            'licencia_identificacion_tecnologia' => 'Identificación Tecnología',
            'observacion' => 'Observacion'
        ];
    }

    public function getSucursales(){
 
        return $this->hasOne(Sucursales::className(), ['sucursal_id' => 'licencia_sucursal_id']);
    }

    public function getTipolicencia(){

        return $this->hasOne(TiposDetalles::className(), ['tipo_detalle_id' => 'licencia_tipo_licencia_id']);
    }
    public function getVersion(){

        return $this->hasOne(TiposDetalles::className(), ['tipo_detalle_id' => 'licencia_version'])->from(['t2' => TiposDetalles::tableName()]);
    }
    public function getEstado(){

        return $this->hasOne(TiposDetalles::className(), ['tipo_detalle_id' => 'licencia_estado_id'])->from(['t3' => TiposDetalles::tableName()]);
    }
    

    
}

controllers/LicenciasController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Licencias;
use app\models\LicenciasSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\TiposDetalles;
use yii\db\Query;
use yii\web\UploadedFile;
use yii\filters\AccessControl;
use app\models\User;

/**
 * LicenciasController implements the CRUD actions for Licencias model.
 */
class LicenciasController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'user', 'admin','index','view','create','update'],
                'rules' => [
                    [
                        //El administrador tiene permisos sobre las siguientes acciones
                        'actions' => ['logout', 'admin','index','view','create','update'],
                        //Esta propiedad establece que tiene permisos
                        'allow' => true,
                        //Usuarios autenticados, el signo ? es para invitados
                        'roles' => ['@'],
                        //Este método nos permite crear un filtro sobre la identidad del usuario
                        //y así establecer si tiene permisos o no
                        'matchCallback' => function ($rule, $action) {
                            //Llamada al método que comprueba si es un administrador
                            return User::isUserAdmin(Yii::$app->user->identity->id);
                        },
                    ],
                    [
                       //Los usuarios de recaudo tienen permisos sobre las siguientes acciones
                       'actions' => ['logout', 'user','index','view','create','update'],
                       //Esta propiedad establece que tiene permisos
                       'allow' => true,
                       //Usuarios autenticados, el signo ? es para invitados
                       'roles' => ['@'],
                       //Este método nos permite crear un filtro sobre la identidad del usuario
                       //y así establecer si tiene permisos o no
                       'matchCallback' => function ($rule, $action) {
                          //Llamada al método que comprueba si es un usuario de recaudo
                          return User::isUserLinalca(Yii::$app->user->identity->id);
                      },
                    ],
                ],
            ],
             //Controla el modo en que se accede a las acciones, en este ejemplo a la acción logout
             //sólo se puede acceder a través del método post
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Licencias models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new LicenciasSearch();
        $model = Licencias::find()->All();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'model' => $model,
        ]);    
    }    

    /**
     * Displays a single Licencias model.
     * @param integer $id
     * @return mixed
     *
     */
    public function actionView($id)
    {
        
        // se instancia la Clase Query.
        $query = new Query();
        $connection = Yii::$app->db;

        $query = $connection->createCommand('SELECT     *,
                                                        (select tipo_detalle_nombre from tipos_detalles where tipo_detalle_id = licencia_tipo_licencia_id) as producto, 
                                                        (select tipo_detalle_nombre from tipos_detalles where tipo_detalle_id = licencia_version) as version_nombre,
                                                        (select     tipo_nombre 
                                                            from    tipos_detalles 
                                                                    join tipos on (tipo_detalle_tipo_id = tipo_id)
                                                            where   tipo_detalle_id = licencia_tipo_licencia_id) as tipo, 
                                                        (select sucursal_nombre from sucursales where sucursal_id = equipo_sucursal_id) as sucursal,
                                                        (select area_nombre from areas where area_id = equipo_area_id) as area

                                                from    licencias 
                                                        join equipos on (licencia_equipo_id = equipo_id)
                                                        join funcionarios on (equipo_usuario_id = funcionario_id)
                                                where   1=1
                                                        and licencia_id ='.$id
                                                );
        $licencias = $query->queryAll();
        // echo "<pre>";
        // print_r($licencias);die();


        return $this->render('view', [
            'model' => $this->findModel($id),
            'licencias' => $licencias,
        ]);
    }

    /**
     * Creates a new Licencias model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Licencias();

        if ($model->load(Yii::$app->request->post()) /*&& $model->save()*/) {

            

            $model->licencia_equipo_id = $_REQUEST['select-funcionarios'];
            $model->licencia_sucursal_id = $_REQUEST['select-sucusales'];
            $model->licencia_tipo_licencia_id = $_REQUEST['select-tiposD'];

            if ($model->save()) {

               return $this->redirect(['view', 'id' => $model->licencia_id]);
            }

            
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Licencias model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {       
        //    $obs = $_REQUEST['licencia_especificaciones'];
        //    $id = $_REQUEST['id'];
           
           $idlic = Licencias::find()->where(['licencia_id' =>$id])->all(); 
           $usuario = Yii::$app->user->identity->id;           
           $dia = date('Y-m-d H:i:s');
           
        $model = $this->findModel($id); 
        // echo '<pre>';
        // print_r($observacion);
        // die;                 

        if ($model->load(Yii::$app->request->post()) && $model->save()) {           
            $query = new Query();
            $connection = Yii::$app->db;                      
            foreach($idlic as $licencia){ 
             //Query para historico de la licencia    
                $query = $connection->createCommand()->insert('historico_licencias',
                                                                ['historico_licencia_id' => $licencia['licencia_id'],
                                                                'licencia_equipo_id' => $licencia['licencia_equipo_id'],
                                                                'licencia_tipo_licencia_id' => $licencia['licencia_tipo_licencia_id'],
                                                                'licencia_numero' => $licencia['licencia_numero'],
                                                                'licencia_version' => $licencia['licencia_version'],
                                                                'licencia_especificaciones' => $licencia['licencia_especificaciones'],
                                                                'licencia_estado_id' => $licencia['licencia_estado_id'],
                                                                'licencia_sucursal_id' => $licencia['licencia_sucursal_id'],
                                                                'licencia_identificacion_tecnologia' => $licencia['licencia_identificacion_tecnologia'],
                                                                'usuario_modifica' => $usuario,
                                                                'fecha_creacion' => $dia,
                                                                'proceso_id' =>26,
                                                                'observacion' =>$_REQUEST['Licencias']['licencia_especificaciones'],
                                                                ])->execute(); 
               
            }           
                  
            return $this->redirect(['view', 'id' => $model->licencia_id]);
        } else {                      
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Licencias model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }


    public function actionLists($id){
     
        $countMunicipios = TiposDetalles::find()->where(['tipo_detalle_tipo_id'=>$id])->count();

        $tiposDetalles = TiposDetalles::find()->where(['tipo_detalle_tipo_id'=>$id])->all();

        if($countMunicipios > 0){
            echo "<option>[--Seleccione Licencia--]</option>";
            foreach ($tiposDetalles as $tiposDetalle) {

views/licencias/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Sucursales;
use app\models\Funcionarios;
use app\models\Tipos;
use app\models\TiposDetalles;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $model app\models\Licencias */
/* @var $form yii\widgets\ActiveForm */

// print_r($model);die();
// echo "<pre>";
?>
 <script src="<?php echo Url::base(); ?>/js/jquery-1.11.3.min.js"></script>

<div class="licencias-form">

    <?php $form = ActiveForm::begin(); ?>
    <div class="form-row">
        <div class="col-lg-12">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Panel de licencia</h3>                    
                </div>
                <div class="form-row">
                    <div class="col-lg-12">
                     <div class="card card-primary">
                        <div class="card-header">
                            <h4 class="card-title">Información general</h4>
                        </div></br>
                        <div class="form-row">
                           <div class="col-md-6 mb3">
                             <?= $form->field($model, 'licencia_identificacion_tecnologia')->textInput(['maxlength' => true]) ?>
                           </div>
                           <div class="col-md-6 mb3">
                                <?= Html::label('Sucursal', 'select-sucusales', ['class'=>'control-label']) ?>
                                    <?= Html::dropDownList(
                                        'select-sucusales',
                                        $model->licencia_sucursal_id,
                                        ArrayHelper::map(Sucursales::find()->orderBy(['sucursal_nombre'=>SORT_ASC])->all(),'sucursal_id', 'sucursal_nombre'),
                                    [
                                            'class'=>'form-control',
                                            'prompt'=>'[-- Seleccione Sucursal --]',
                                            'value'=> 0,
                                            'id' => 'select-sucusales',
                                            'required' => 'required',
                                            'onchange' => '$.post("index.php?r=funcionarios/lists&id='.'"+$(this).val(), function(data){
                                                    $("#select-funcionarios").val("");
                                                    $("#select-funcionarios").html(data);
                                                    $("#select-funcionarios").removeAttr("disabled");
                                            })',
                                        ]) 
                                ?>
                           </div>
                           <div class="col-md-12 mb3">
                           <?= Html::label('Funcionario', 'select-funcionarios2', ['class'=>'control-label']) ?>
                                    <?= Html::dropDownList(
                                        'select-funcionarios',
                                        $model->licencia_equipo_id,
                                        ArrayHelper::map(funcionarios::find()
                                                                ->orderBy(['funcionario_nombres'=>SORT_ASC])
                                                                ->all(), 'equipos.equipo_id', 'funcionario_nombres'),
                                        [
                                            'class'=>'form-control',
                                            'prompt'=>'[-- Seleccione Funcionario --]',
                                            'value'=> 0,
                                            'required' => 'required',
                                            'id'=>'select-funcionarios',
                                            'onchange' => '',
                                            'disabled' => 'disabled',                            
                                        ]) 
                                    ?>
                           </div>
                        </div>
                      </div>
                    </div>                    
                </div>
                <div class="form-row">
                    <div class="col-lg-12">
                        <div class="card card-primary">
                            <div class="card-header">
                                <h4 class="card-title">Informacición técnica</h4>
                            </div></br>                                                                                
                            <div class="form-row">
                              <div class="col-md-6 mb-3">
                                <?= Html::label('Tipo de licencia', 'select-tipo1', ['class'=>'control-label']) ?>
                                        <?= Html::dropDownList(
                                            'select-tipol',
                                            '',
                                            ArrayHelper::map(Tipos::find()
                                                                    ->Where(['in','tipo_id', array(3,4)])
                                                                    ->orderBy(['tipo_nombre'=>SORT_ASC])->all(),'tipo_id', 'tipo_nombre'),
                                        [
                                                'class'=>'form-control',
                                                'prompt'=>'[-- Seleccione Tipo de Licencia --]',
                                                'value'=> 0,
                                                'id' => 'select-tipo1',
                                                'required' => 'required',
                                                'onchange' => '$.post("index.php?r=licencias/lists&id='.'"+$(this).val(), function(data){
                                                        $("#select-licencias").val("");
                                                        $("#select-licencias").html(data);
                                                        $("#select-licencias").removeAttr("disabled");
                                                })',
                                            ]) 
                                        ?>
                              </div>
                              <div class="col-md-6 mb-3">
                                <?= Html::label('Producto', 'select-tiposD', ['class'=>'control-label']) ?>
                                    <?= Html::dropDownList(
                                        'select-tiposD',
                                        $model->licencia_tipo_licencia_id,
                                        ArrayHelper::map(TiposDetalles::find()
                                                                ->orderBy(['tipo_detalle_nombre'=>SORT_ASC])
                                                                ->all(), 'tipo_detalle_id', 'tipo_detalle_nombre'),
                                        [
                                            'class'=>'form-control',
                                            'prompt'=>'[-- Seleccione Licencia --]',
                                            'value'=> 0,
                                            'id'=>'select-licencias',
                                            'onchange' => '',
                                            'disabled' => 'disabled',
                                        ]) 
                                    ?>
                              </div> 
                              <div class="col-md-6 mb3">
                               <?= $form->field($model, 'licencia_version')->dropDownList(ArrayHelper::map(TiposDetalles::find()->
                                                    where(['tipo_detalle_tipo_id'=>12])
                                                        ->orderBy(['tipo_detalle_nombre'=>SORT_ASC])->all(), 'tipo_detalle_id', 'tipo_detalle_nombre'), 
                                                [
                                                'prompt'=>'[-- Seleccione Tipo--]',
                                                ]
                                            ) ?>
                                    <div class="help-block"></div>
                              </div> 
                              <div class="col-md-6 mb3">
                                 <?= $form->field($model, 'licencia_numero')->textInput(['maxlength' => true]) ?>
                              </div>
                              <div class="col-md-12 mb3">
                                 <?= $form->field($model, 'licencia_especificaciones')->textarea(['rows' => 6]) ?>
                              </div>
                            </div>
                        </div>
                            <?php ActiveForm::end(); ?>
                    </div>        
                </div>
                <div class="col-lg-12">                                    
                    <?= Html::submitButton($model->isNewRecord ? 'Crear' : 'Guardar', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-success']) ?>
                </div>                             
            </div>            
        </div>
    </div>            
</div>
<script>
    $(document).ready(function(){
   //código a ejecutar cuando el DOM está listo para recibir instrucciones.
    
    });
</script>

views/licencias/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\LicenciasSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="licencias-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'licencia_id') ?>

    <?= $form->field($model, 'licencia_equipo_id') ?>

    <?= $form->field($model, 'licencia_tipo_licencia_id') ?>

    <?= $form->field($model, 'licencia_numero') ?>

    <?= $form->field($model, 'licencia_version') ?>

    <?php // echo $form->field($model, 'licencia_especificaciones') ?>

    <?php // echo $form->field($model, 'licencia_estado_id') ?>

    <?php // echo $form->field($model, 'licencia_sucursal_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/licencias/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Licencias */

$this->title = 'Registro de Licencia';
$this->params['breadcrumbs'][] = ['label' => 'Licencias', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="licencias-create">

    <!-- <div class="alert alert-success" role="alert"> <h3><?= Html::encode($this->title) ?></h3></div> -->

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/licencias/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

$this->title = 'Licencias';
$this->params['breadcrumbs'][] = $this->title;
?>
    
<div class="card card-purple">
    <div class="card-header">
    <!-- <h3 class="card-title">DataTable with default features</h3> -->Resultados encontrados
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <p>
            <?= Html::a('Registrar licencia', ['licencias/create'], ['class' => 'btn btn-success']) ?>
        </p>
        <div class="col-lg-12">
            <div class="row">
             <div class="table-responsive">              
                <table id="example1" class="table table-bordered table-hover table-striped">
                    <thead>
                    <tr>
                    <th>Tipo Licencia</th>
                    <th>Producto</th>
                    <th>Versión</th>
                    <th>Identificación tecnologia</th>
                    <th>Estado</th>
                    <th>Acción</th>                    
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($model as $key => $value) {?>
                    <tr>
                        <td><?php echo $value->tipolicencia->tiposd->tipo_nombre ?></td>
                        <td><?php echo $value->tipolicencia->tipo_detalle_nombre ?></td>
                        <td><?php echo $value->version->tipo_detalle_nombre ?></td>
                        <td><?php echo $value['licencia_identificacion_tecnologia'] ?></td>
                        <td><?php echo $value->estado->tipo_detalle_nombre ?></td>
                        
                       
                        <td>
                            <?= Html::a('Ver', ['licencias/view', 'id'=> $value['licencia_id']], ['class' => 'btn btn-primary btn-block ']) ?>
                            <?= Html::a('Actualizar', ['licencias/update', 'id'=> $value['licencia_id']], ['class' => 'btn btn-warning btn-block ']) ?>
                        </td>
                    </tr>
                    <?php } ?>
                    </tbody>
                </table>
              </div>  
            </div>
        </div>    
    </div>
    <!-- /.card-body -->
</div>
<script>
  $(function () {
    $("#example1").DataTable({
      "language": {
          "sProcessing":    "Procesando...",
          "sLengthMenu":    "Mostrar _MENU_ registros",
          "sZeroRecords":   "No se encontraron resultados",
          "sEmptyTable":    "Ningún dato disponible en esta tabla",
          "sInfo":          "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
          "sInfoEmpty":     "Mostrando registros del 0 al 0 de un total de 0 registros",
          "sInfoFiltered":  "(filtrado de un total de _MAX_ registros)",
          "sInfoPostFix":   "",
          "sSearch":        "Buscar:",
          "sUrl":           "",
          "sInfoThousands":  ",",
          "sLoadingRecords": "Cargando...",
          "oPaginate": {
              "sFirst":    "Primero",
              "sLast":    "Último",
              "sNext":    "Siguiente",
              "sPrevious": "Anterior"
          },
          "oAria": {
              "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
              "sSortDescending": ": Activar para ordenar la columna de manera descendente"
          }
      },
      "responsive": true, "lengthChange": false, "autoWidth": false,
      "buttons": ["copy", "csv", "excel"]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');


    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
</script>

views/licencias/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Licencias */

$this->title = 'Actualizacion de Licencia : ' . ' ' . $model->tipolicencia->tipo_detalle_nombre;
$this->params['breadcrumbs'][] = ['label' => 'Licencias', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->licencia_id, 'url' => ['view', 'id' => $model->licencia_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="licencias-update">

    <!-- <div class="alert alert-success" role="alert"> <h3><?= Html::encode($this->title) ?></h3></div> -->
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>